# Generated by Django 4.1.7 on 2023-07-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('hash_id', models.AutoField(primary_key=True, serialize=False)),
                ('hash_name', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'hashtags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(default='-', max_length=100)),
                ('prod_link', models.CharField(default='-', max_length=300)),
                ('prod_price', models.IntegerField(default=0)),
                ('prod_thumbnail', models.CharField(default='-', max_length=300)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductHashtag',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('prod_hash_id', models.AutoField(primary_key=True, serialize=False)),
                ('hash_id', models.ForeignKey(db_column='hash_id', on_delete=django.db.models.deletion.PROTECT, to='products.hashtag')),
                ('prod_id', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'db_table': 'products_hashtags',
                'managed': True,
            },
        ),
    ]
