name: CI
on:
  push:
    branches:
      - 'feat/**'
  pull_request:
    branches:
      - 'feat/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    env:
      working-directory: ./web/apps/

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        python3 manage.py test --settings=config.settings.development
        python3 manage.py test
      working-directory: ${{ env.working-directory }}
