name: CI
on:
  push:
    branches:
      - 'feat/**'
  pull_request:
    branches:
      - 'feat/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./web/apps/

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        python3 manage.py test
      working-directory: ${{ env.working-directory }}